### ISSUE TITLE
more

### ISSUE THREAD

**Issue by ignatandrei** [ignatandrei/RSCG_Examples#265]
https://www.nuget.org/packages/Hexa.Protobuf
https://www.nuget.org/packages/FactoryGenerator.Attributes
https://www.nuget.org/packages/Neon.Roslyn
https://www.nuget.org/packages/Antelcat.AutoGen
https://www.nuget.org/packages/Steelax.EasyRoslyn
https://github.com/specklesystems/ProxyGenerator

**Comment by SzymonHalucha** [comment]
Hello Andrei,
I made another two generators:
[Minerals.AutoDomain](https://github.com/SzymonHalucha/Minerals.AutoDomain)
[Minerals.AutoCQRS](https://github.com/SzymonHalucha/Minerals.AutoCQRS)

**Comment by ignatandrei** [comment]
I have put on the list of the examples that I should check . Thanks for adding this!
