### ISSUE TITLE
+ DI source generators?

### ISSUE THREAD

**Issue by lsoft** [ignatandrei/RSCG_Examples#343]
Hello! Maybe you would be interested in adding 2 SG based DI repos:

- https://github.com/DevTeam/Pure.DI
- https://github.com/lsoft/DpdtInject

**Comment by ignatandrei** [comment]
I will verify and add ASAP

**Comment by ignatandrei** [comment]
I will add them here;
https://ignatandrei.github.io/RSCG_Examples/v2/docs/rscg-examples#dependencyinjection

**Comment by ignatandrei** [comment]
DpdtInject uses ISourceGenerator, not IIncrementalGenerator
https://github.com/dotnet/roslyn/blob/main/docs/features/incremental-generators.md

Please implement this- because it gives better experience to the developers.

**Comment by ignatandrei** [comment]
For other, I have opened an issue
https://github.com/DevTeam/Pure.DI/issues/78

**Comment by ignatandrei** [comment]
Thank you. I have added at

https://ignatandrei.github.io/RSCG_Examples/v2/docs/Pure.DI
