### ISSUE TITLE
[RSCG number 14 : Property Expression Generator] Image rendered with error

### ISSUE THREAD

**Issue by Dblm0** [ignatandrei/RSCG_Examples#6]
One of the images of web version is rendered incorrectly
https://ignatandrei.github.io/RSCG_Examples/images/Property%20Expression%20Generator/Usage.cs.png
![](https://ignatandrei.github.io/RSCG_Examples/images/Property%20Expression%20Generator/Usage.cs.png)

**Comment by ignatandrei** [comment]
Thanks for feedback
